# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/87a5f0a5-3dee-4630-951d-f546f06f8913";
      fsType = "btrfs";
    };

  fileSystems."/media/HDD" =
    { device = "/dev/disk/by-uuid/9c351aa9-2a86-4b3b-8be8-b084a0892d9b";
      fsType = "btrfs";
    };

  fileSystems."/media/SSDg" =
    { device = "/dev/disk/by-uuid/fad9cbc9-a5b3-4587-bab7-b8412130af2e";
      fsType = "btrfs";
    };

  fileSystems."/media/SSM" =
    { device = "/dev/disk/by-uuid/84e0db19-6381-4bf8-9687-bb58b9db7135";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/19F8-6FD7";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
